[package]
name = "match_runner"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
reversi_core = { path = "../reversi_core" }
indicatif = "0.17.11"
colored = "3.0.0"

[target.'cfg(not(windows))'.dependencies]
shlex = "1.3.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.60.2", features = ["Win32_Foundation", "Win32_UI_Shell", "Win32_System_Threading"] }

[[bin]]
name = "match-runner"
path = "src/main.rs"
