[package]
name = "reversi-core"
version.workspace = true
edition.workspace = true
license.workspace = true
autobenches = false

[features]
search-stats = []

[dependencies]
byteorder = "1.5"
lock_api = "0.4"
rapidhash = { version = "4.4", features = ["unsafe"] }
zstd = "0.13"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Memory",
    "Win32_System_Threading",
] }

[dev-dependencies]
criterion = "0.8"
rand = "0.10"

[[bench]]
name = "network"
harness = false

[[bench]]
name = "pattern_feature"
harness = false

[[bench]]
name = "perft"
harness = false

[[bench]]
name = "bitboard"
harness = false

[[bench]]
name = "flip"
harness = false

[[bench]]
name = "solve1"
harness = false

[[bench]]
name = "stability"
harness = false

[[bench]]
name = "move_list"
harness = false

[[bench]]
name = "endgame"
harness = false
