[package]
name = "ffotest"
version.workspace = true
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
colored = "3.0.0"
num-format = "0.4.4"

reversi_core = { path = "../reversi_core" }

[build-dependencies]
build_common = { workspace = true }
