[package]
name = "automatch"
version.workspace = true
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
reversi_core = { path = "../reversi_core" }
indicatif = "0.17"
colored = "2"
